allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@double-great/stylelint-a11y@3.5.4'
  - '@tanstack/history@1.162.4'
  - '@tanstack/react-router-devtools@1.167.2'
  - '@tanstack/react-router@1.170.36'
  - '@tanstack/router-core@1.171.30'
  - '@tanstack/router-devtools-core@1.168.2'
  - '@tanstack/router-generator@1.167.36'
  - '@tanstack/router-plugin@1.168.38'
  - zod@4.6.4
